In [1]:
import tensorflow as tf
import numpy as np
from tensorflow import keras

In [2]:
model = keras.Sequential([keras.layers.Dense(1,input_shape=[1])])
model.compile(optimizer = 'adam', loss = 'mean_squared_error')

In [3]:
xs = np.random.random((10000, 1))*21
ys = 3*xs - 5

In [4]:
model.fit(xs,ys,validation_split=0.2,epochs = 1000, batch_size = 256)

In [12]:
print(round(model.predict([1000])[0][0]))

1/1 [==============================] - 0s 104ms/step
2995


In [12]:
import numpy as np

# Define the sigmoid function and its derivative
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

# Define the training data
x_train = np.random.randint(1, 11, size=(10000, 1))
y_train = x_train + 3

print(x_train)
print(y_train)
# Define the model architecture
input_units = 1
hidden_units = 2
output_units = 1

# Initialize the weights and biases
weights_ih = np.random.uniform(size=(input_units, hidden_units))
weights_ho = np.random.uniform(size=(hidden_units, output_units))
bias_h = np.random.uniform(size=(1, hidden_units))
bias_o = np.random.uniform(size=(1, output_units))

# Set the learning rate and number of epochs
learning_rate = 0.1
epochs = 5000

# Train the model
for epoch in range(epochs):
    # Forward propagation
    hidden_layer_input = np.dot(x_train, weights_ih) + bias_h
    hidden_layer_output = sigmoid(hidden_layer_input)
    output_layer_input = np.dot(hidden_layer_output, weights_ho) + bias_o
    predicted_output = sigmoid(output_layer_input)

    # Calculate the error
    error = y_train - predicted_output

    # Backpropagation
    d_predicted_output = error * sigmoid_derivative(predicted_output)
    error_hidden_layer = d_predicted_output.dot(weights_ho.T)
    d_hidden_layer = error_hidden_layer * sigmoid_derivative(hidden_layer_output)

    # Update the weights and biases
    weights_ho += hidden_layer_output.T.dot(d_predicted_output) * learning_rate
    bias_o += np.sum(d_predicted_output, axis=0, keepdims=True) * learning_rate
    weights_ih += x_train.T.dot(d_hidden_layer) * learning_rate
    bias_h += np.sum(d_hidden_layer, axis=0, keepdims=True) * learning_rate


[[ 5]
 [ 6]
 [10]
 ...
 [ 9]
 [ 1]
 [ 2]]
[[ 8]
 [ 9]
 [13]
 ...
 [12]
 [ 4]
 [ 5]]


In [13]:
x_test = np.array([[5], [10], [7]])
hidden_layer_input = np.dot(x_test, weights_ih) + bias_h
hidden_layer_output = sigmoid(hidden_layer_input)
output_layer_input = np.dot(hidden_layer_output, weights_ho) + bias_o
print(predicted_output)

[[1.]
 [1.]
 [1.]
 ...
 [1.]
 [1.]
 [1.]]
